version: "3.8"

services:
  db:
    image: postgres:12.7
    restart: on-failure
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=111"
      - "POSTGRES_DB=to-do"
    ports:
      - "5632:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
volumes:
  pgdata:
